'use client'
import React from 'react'
import { Toaster } from 'react-hot-toast'
import './globals.css'

import { Layouts } from '@/components'

import { Stateagus } from '@/context/Stateagus'

import { QueryClient, QueryClientProvider } from 'react-query';
import { ReactQueryDevtools } from 'react-query/devtools'; // (Optional) Devtools for debugging

// Create a new instance of QueryClient
const queryClient = new QueryClient();


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


 function RootLayout({ children }) {
  return (
   
  <html lang="en">
      <body>
      <QueryClientProvider client={queryClient}>
      <Stateagus>
     <Layouts>
      <Toaster/>
      {  children}
     
      </Layouts>
      </Stateagus>
      </QueryClientProvider>
      </body>
      </html>
    
    
      

     
      
   
  )
}


export default RootLayout
