"use client"
import React from 'react'
import { Toaster } from 'react-hot-toast'
import './globals.css'

import { Layouts } from '@/components'

import { Stateagus } from '@/context/Stateagus'

import { QueryClient, QueryClientProvider } from 'react-query';

// Create a new instance of QueryClient
const queryClient = new QueryClient();


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


 function RootLayout({ children }) {
  return (
   
  <html lang="en">
    <head>
        <title>Title</title>
        <meta name='description' content='Description' />
      </head>
      <body>
      <QueryClientProvider client={queryClient}>
      <Stateagus>
     <Layouts>
      <Toaster/>
      {  children}
     
      </Layouts>
      </Stateagus>
      </QueryClientProvider>
      </body>
      </html>
    
    
      

     
      
   
  )
}


export default RootLayout
